// Code generated by protoc-gen-go.
// source: gameProto.proto
// DO NOT EDIT!

/*
Package gameProto is a generated protocol buffer package.

It is generated from these files:
	gameProto.proto

It has these top-level messages:
	ErrorMsgS2C
	AgainConnectC2S
	AgainConnectS2C
	OtherLoginS2C
	ConnectSuccessS2C
	Person
	UserLoginC2S
	UserLoginS2C
	GetUserInfoC2S
	GetUserInfoS2C
*/
package gameProto

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

// 错误消息
type ErrorMsgS2C struct {
	ErrorID          *int32 `protobuf:"varint,1,req" json:"ErrorID,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ErrorMsgS2C) Reset()         { *m = ErrorMsgS2C{} }
func (m *ErrorMsgS2C) String() string { return proto.CompactTextString(m) }
func (*ErrorMsgS2C) ProtoMessage()    {}

func (m *ErrorMsgS2C) GetErrorID() int32 {
	if m != nil && m.ErrorID != nil {
		return *m.ErrorID
	}
	return 0
}

// 重新连接C2S
type AgainConnectC2S struct {
	SessionID        *uint64 `protobuf:"varint,1,req" json:"SessionID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AgainConnectC2S) Reset()         { *m = AgainConnectC2S{} }
func (m *AgainConnectC2S) String() string { return proto.CompactTextString(m) }
func (*AgainConnectC2S) ProtoMessage()    {}

func (m *AgainConnectC2S) GetSessionID() uint64 {
	if m != nil && m.SessionID != nil {
		return *m.SessionID
	}
	return 0
}

// 重新连接S2C
type AgainConnectS2C struct {
	SessionID        *uint64 `protobuf:"varint,1,req" json:"SessionID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AgainConnectS2C) Reset()         { *m = AgainConnectS2C{} }
func (m *AgainConnectS2C) String() string { return proto.CompactTextString(m) }
func (*AgainConnectS2C) ProtoMessage()    {}

func (m *AgainConnectS2C) GetSessionID() uint64 {
	if m != nil && m.SessionID != nil {
		return *m.SessionID
	}
	return 0
}

// 其他客户端登录S2C
type OtherLoginS2C struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *OtherLoginS2C) Reset()         { *m = OtherLoginS2C{} }
func (m *OtherLoginS2C) String() string { return proto.CompactTextString(m) }
func (*OtherLoginS2C) ProtoMessage()    {}

// 连接成功S2C
type ConnectSuccessS2C struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *ConnectSuccessS2C) Reset()         { *m = ConnectSuccessS2C{} }
func (m *ConnectSuccessS2C) String() string { return proto.CompactTextString(m) }
func (*ConnectSuccessS2C) ProtoMessage()    {}

// 用户数据
type Person struct {
	ID               *uint64 `protobuf:"varint,1,req" json:"ID,omitempty"`
	Name             *string `protobuf:"bytes,2,req" json:"Name,omitempty"`
	Money            *int32  `protobuf:"varint,3,req" json:"Money,omitempty"`
	SessionID        *uint64 `protobuf:"varint,4,req" json:"SessionID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}

func (m *Person) GetID() uint64 {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return 0
}

func (m *Person) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Person) GetMoney() int32 {
	if m != nil && m.Money != nil {
		return *m.Money
	}
	return 0
}

func (m *Person) GetSessionID() uint64 {
	if m != nil && m.SessionID != nil {
		return *m.SessionID
	}
	return 0
}

// 用户登录C2S
type UserLoginC2S struct {
	UserName         *string `protobuf:"bytes,1,req" json:"UserName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UserLoginC2S) Reset()         { *m = UserLoginC2S{} }
func (m *UserLoginC2S) String() string { return proto.CompactTextString(m) }
func (*UserLoginC2S) ProtoMessage()    {}

func (m *UserLoginC2S) GetUserName() string {
	if m != nil && m.UserName != nil {
		return *m.UserName
	}
	return ""
}

// 用户登录S2C
type UserLoginS2C struct {
	UserID           *uint64 `protobuf:"varint,1,req" json:"UserID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UserLoginS2C) Reset()         { *m = UserLoginS2C{} }
func (m *UserLoginS2C) String() string { return proto.CompactTextString(m) }
func (*UserLoginS2C) ProtoMessage()    {}

func (m *UserLoginS2C) GetUserID() uint64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

// 获取用户信息C2S
type GetUserInfoC2S struct {
	UserID           *uint64 `protobuf:"varint,1,req" json:"UserID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetUserInfoC2S) Reset()         { *m = GetUserInfoC2S{} }
func (m *GetUserInfoC2S) String() string { return proto.CompactTextString(m) }
func (*GetUserInfoC2S) ProtoMessage()    {}

func (m *GetUserInfoC2S) GetUserID() uint64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

// 获取用户信息S2C
type GetUserInfoS2C struct {
	UserInfo         *Person `protobuf:"bytes,1,req" json:"UserInfo,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetUserInfoS2C) Reset()         { *m = GetUserInfoS2C{} }
func (m *GetUserInfoS2C) String() string { return proto.CompactTextString(m) }
func (*GetUserInfoS2C) ProtoMessage()    {}

func (m *GetUserInfoS2C) GetUserInfo() *Person {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

func init() {
}
