// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.14.0
// source: gameProto.proto

package gameProto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//错误消息(500)
type ErrorNoticeS2C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorCode *int32 `protobuf:"varint,1,req,name=errorCode" json:"errorCode,omitempty"`
}

func (x *ErrorNoticeS2C) Reset() {
	*x = ErrorNoticeS2C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gameProto_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrorNoticeS2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorNoticeS2C) ProtoMessage() {}

func (x *ErrorNoticeS2C) ProtoReflect() protoreflect.Message {
	mi := &file_gameProto_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorNoticeS2C.ProtoReflect.Descriptor instead.
func (*ErrorNoticeS2C) Descriptor() ([]byte, []int) {
	return file_gameProto_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorNoticeS2C) GetErrorCode() int32 {
	if x != nil && x.ErrorCode != nil {
		return *x.ErrorCode
	}
	return 0
}

//客户端ping(1001)
type ClientPingC2S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ClientPingC2S) Reset() {
	*x = ClientPingC2S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gameProto_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientPingC2S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientPingC2S) ProtoMessage() {}

func (x *ClientPingC2S) ProtoReflect() protoreflect.Message {
	mi := &file_gameProto_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientPingC2S.ProtoReflect.Descriptor instead.
func (*ClientPingC2S) Descriptor() ([]byte, []int) {
	return file_gameProto_proto_rawDescGZIP(), []int{1}
}

//用户登录C2S(2001)
type UserLoginC2S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account *string `protobuf:"bytes,1,req,name=account" json:"account,omitempty"`
}

func (x *UserLoginC2S) Reset() {
	*x = UserLoginC2S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gameProto_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserLoginC2S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLoginC2S) ProtoMessage() {}

func (x *UserLoginC2S) ProtoReflect() protoreflect.Message {
	mi := &file_gameProto_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLoginC2S.ProtoReflect.Descriptor instead.
func (*UserLoginC2S) Descriptor() ([]byte, []int) {
	return file_gameProto_proto_rawDescGZIP(), []int{2}
}

func (x *UserLoginC2S) GetAccount() string {
	if x != nil && x.Account != nil {
		return *x.Account
	}
	return ""
}

//用户登录S2C(2002)
type UserLoginS2C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token *string `protobuf:"bytes,1,req,name=token" json:"token,omitempty"`
}

func (x *UserLoginS2C) Reset() {
	*x = UserLoginS2C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gameProto_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserLoginS2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLoginS2C) ProtoMessage() {}

func (x *UserLoginS2C) ProtoReflect() protoreflect.Message {
	mi := &file_gameProto_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLoginS2C.ProtoReflect.Descriptor instead.
func (*UserLoginS2C) Descriptor() ([]byte, []int) {
	return file_gameProto_proto_rawDescGZIP(), []int{3}
}

func (x *UserLoginS2C) GetToken() string {
	if x != nil && x.Token != nil {
		return *x.Token
	}
	return ""
}

//其他客户端登录S2C(2004)
type UserOtherLoginNoticeS2C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UserOtherLoginNoticeS2C) Reset() {
	*x = UserOtherLoginNoticeS2C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gameProto_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserOtherLoginNoticeS2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOtherLoginNoticeS2C) ProtoMessage() {}

func (x *UserOtherLoginNoticeS2C) ProtoReflect() protoreflect.Message {
	mi := &file_gameProto_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOtherLoginNoticeS2C.ProtoReflect.Descriptor instead.
func (*UserOtherLoginNoticeS2C) Descriptor() ([]byte, []int) {
	return file_gameProto_proto_rawDescGZIP(), []int{4}
}

//用户数据
type UserInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    *uint64 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Name  *string `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Money *int32  `protobuf:"varint,3,req,name=money" json:"money,omitempty"`
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gameProto_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_gameProto_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_gameProto_proto_rawDescGZIP(), []int{5}
}

func (x *UserInfo) GetId() uint64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *UserInfo) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UserInfo) GetMoney() int32 {
	if x != nil && x.Money != nil {
		return *x.Money
	}
	return 0
}

//获取用户信息C2S(3001)
type UserGetInfoC2S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token *string `protobuf:"bytes,1,req,name=token" json:"token,omitempty"`
}

func (x *UserGetInfoC2S) Reset() {
	*x = UserGetInfoC2S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gameProto_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserGetInfoC2S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGetInfoC2S) ProtoMessage() {}

func (x *UserGetInfoC2S) ProtoReflect() protoreflect.Message {
	mi := &file_gameProto_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGetInfoC2S.ProtoReflect.Descriptor instead.
func (*UserGetInfoC2S) Descriptor() ([]byte, []int) {
	return file_gameProto_proto_rawDescGZIP(), []int{6}
}

func (x *UserGetInfoC2S) GetToken() string {
	if x != nil && x.Token != nil {
		return *x.Token
	}
	return ""
}

//获取用户信息S2C(3002)
type UserGetInfoS2C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *UserInfo `protobuf:"bytes,1,req,name=data" json:"data,omitempty"`
}

func (x *UserGetInfoS2C) Reset() {
	*x = UserGetInfoS2C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gameProto_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserGetInfoS2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGetInfoS2C) ProtoMessage() {}

func (x *UserGetInfoS2C) ProtoReflect() protoreflect.Message {
	mi := &file_gameProto_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGetInfoS2C.ProtoReflect.Descriptor instead.
func (*UserGetInfoS2C) Descriptor() ([]byte, []int) {
	return file_gameProto_proto_rawDescGZIP(), []int{7}
}

func (x *UserGetInfoS2C) GetData() *UserInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

//用户加入聊天C2S(4001)
type UserJoinChatC2S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token *string `protobuf:"bytes,1,req,name=token" json:"token,omitempty"`
}

func (x *UserJoinChatC2S) Reset() {
	*x = UserJoinChatC2S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gameProto_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserJoinChatC2S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserJoinChatC2S) ProtoMessage() {}

func (x *UserJoinChatC2S) ProtoReflect() protoreflect.Message {
	mi := &file_gameProto_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserJoinChatC2S.ProtoReflect.Descriptor instead.
func (*UserJoinChatC2S) Descriptor() ([]byte, []int) {
	return file_gameProto_proto_rawDescGZIP(), []int{8}
}

func (x *UserJoinChatC2S) GetToken() string {
	if x != nil && x.Token != nil {
		return *x.Token
	}
	return ""
}

//用户加入聊天S2C(4002)
type UserJoinChatS2C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UserJoinChatS2C) Reset() {
	*x = UserJoinChatS2C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gameProto_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserJoinChatS2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserJoinChatS2C) ProtoMessage() {}

func (x *UserJoinChatS2C) ProtoReflect() protoreflect.Message {
	mi := &file_gameProto_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserJoinChatS2C.ProtoReflect.Descriptor instead.
func (*UserJoinChatS2C) Descriptor() ([]byte, []int) {
	return file_gameProto_proto_rawDescGZIP(), []int{9}
}

//用户聊天消息C2S(4003)
type UserChatC2S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg *string `protobuf:"bytes,1,req,name=msg" json:"msg,omitempty"`
}

func (x *UserChatC2S) Reset() {
	*x = UserChatC2S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gameProto_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserChatC2S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserChatC2S) ProtoMessage() {}

func (x *UserChatC2S) ProtoReflect() protoreflect.Message {
	mi := &file_gameProto_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserChatC2S.ProtoReflect.Descriptor instead.
func (*UserChatC2S) Descriptor() ([]byte, []int) {
	return file_gameProto_proto_rawDescGZIP(), []int{10}
}

func (x *UserChatC2S) GetMsg() string {
	if x != nil && x.Msg != nil {
		return *x.Msg
	}
	return ""
}

//用户聊天消息S2C(4004)
type UserChatNoticeS2C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   *uint64 `protobuf:"varint,1,req,name=userId" json:"userId,omitempty"`
	UserName *string `protobuf:"bytes,2,req,name=userName" json:"userName,omitempty"`
	Msg      *string `protobuf:"bytes,3,req,name=msg" json:"msg,omitempty"`
}

func (x *UserChatNoticeS2C) Reset() {
	*x = UserChatNoticeS2C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gameProto_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserChatNoticeS2C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserChatNoticeS2C) ProtoMessage() {}

func (x *UserChatNoticeS2C) ProtoReflect() protoreflect.Message {
	mi := &file_gameProto_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserChatNoticeS2C.ProtoReflect.Descriptor instead.
func (*UserChatNoticeS2C) Descriptor() ([]byte, []int) {
	return file_gameProto_proto_rawDescGZIP(), []int{11}
}

func (x *UserChatNoticeS2C) GetUserId() uint64 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

func (x *UserChatNoticeS2C) GetUserName() string {
	if x != nil && x.UserName != nil {
		return *x.UserName
	}
	return ""
}

func (x *UserChatNoticeS2C) GetMsg() string {
	if x != nil && x.Msg != nil {
		return *x.Msg
	}
	return ""
}

var File_gameProto_proto protoreflect.FileDescriptor

var file_gameProto_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x67, 0x61, 0x6d, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x30, 0x0a, 0x10, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6e, 0x6f, 0x74, 0x69, 0x63,
	0x65, 0x5f, 0x73, 0x32, 0x63, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43,
	0x6f, 0x64, 0x65, 0x22, 0x11, 0x0a, 0x0f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x70, 0x69,
	0x6e, 0x67, 0x5f, 0x63, 0x32, 0x73, 0x22, 0x2a, 0x0a, 0x0e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6c,
	0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x63, 0x32, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x22, 0x26, 0x0a, 0x0e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e,
	0x5f, 0x73, 0x32, 0x63, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20,
	0x02, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x1c, 0x0a, 0x1a, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x6e, 0x6f,
	0x74, 0x69, 0x63, 0x65, 0x5f, 0x73, 0x32, 0x63, 0x22, 0x44, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x04,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x02,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x6e, 0x65,
	0x79, 0x18, 0x03, 0x20, 0x02, 0x28, 0x05, 0x52, 0x05, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x22, 0x28,
	0x0a, 0x10, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x67, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x5f, 0x63,
	0x32, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x02, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x31, 0x0a, 0x10, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x67, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x5f, 0x73, 0x32, 0x63, 0x12, 0x1d, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x29, 0x0a, 0x11, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x6a, 0x6f, 0x69, 0x6e, 0x43, 0x68, 0x61, 0x74, 0x5f, 0x63, 0x32, 0x73,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x13, 0x0a, 0x11, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6a,
	0x6f, 0x69, 0x6e, 0x43, 0x68, 0x61, 0x74, 0x5f, 0x73, 0x32, 0x63, 0x22, 0x21, 0x0a, 0x0d, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x63, 0x32, 0x73, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x5c,
	0x0a, 0x14, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x6e, 0x6f, 0x74, 0x69,
	0x63, 0x65, 0x5f, 0x73, 0x32, 0x63, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x02, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x09,
	0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73,
	0x67, 0x18, 0x03, 0x20, 0x02, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x42, 0x0d, 0x5a, 0x0b,
	0x2e, 0x3b, 0x67, 0x61, 0x6d, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f,
}

var (
	file_gameProto_proto_rawDescOnce sync.Once
	file_gameProto_proto_rawDescData = file_gameProto_proto_rawDesc
)

func file_gameProto_proto_rawDescGZIP() []byte {
	file_gameProto_proto_rawDescOnce.Do(func() {
		file_gameProto_proto_rawDescData = protoimpl.X.CompressGZIP(file_gameProto_proto_rawDescData)
	})
	return file_gameProto_proto_rawDescData
}

var file_gameProto_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_gameProto_proto_goTypes = []interface{}{
	(*ErrorNoticeS2C)(nil),          // 0: error_notice_s2c
	(*ClientPingC2S)(nil),           // 1: client_ping_c2s
	(*UserLoginC2S)(nil),            // 2: user_login_c2s
	(*UserLoginS2C)(nil),            // 3: user_login_s2c
	(*UserOtherLoginNoticeS2C)(nil), // 4: user_otherLogin_notice_s2c
	(*UserInfo)(nil),                // 5: userInfo
	(*UserGetInfoC2S)(nil),          // 6: user_getInfo_c2s
	(*UserGetInfoS2C)(nil),          // 7: user_getInfo_s2c
	(*UserJoinChatC2S)(nil),         // 8: user_joinChat_c2s
	(*UserJoinChatS2C)(nil),         // 9: user_joinChat_s2c
	(*UserChatC2S)(nil),             // 10: user_chat_c2s
	(*UserChatNoticeS2C)(nil),       // 11: user_chat_notice_s2c
}
var file_gameProto_proto_depIdxs = []int32{
	5, // 0: user_getInfo_s2c.data:type_name -> userInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gameProto_proto_init() }
func file_gameProto_proto_init() {
	if File_gameProto_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gameProto_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrorNoticeS2C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gameProto_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientPingC2S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gameProto_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserLoginC2S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gameProto_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserLoginS2C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gameProto_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserOtherLoginNoticeS2C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gameProto_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gameProto_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserGetInfoC2S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gameProto_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserGetInfoS2C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gameProto_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserJoinChatC2S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gameProto_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserJoinChatS2C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gameProto_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserChatC2S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gameProto_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserChatNoticeS2C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gameProto_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gameProto_proto_goTypes,
		DependencyIndexes: file_gameProto_proto_depIdxs,
		MessageInfos:      file_gameProto_proto_msgTypes,
	}.Build()
	File_gameProto_proto = out.File
	file_gameProto_proto_rawDesc = nil
	file_gameProto_proto_goTypes = nil
	file_gameProto_proto_depIdxs = nil
}
