// Code generated by protoc-gen-go.
// source: systemProto.proto
// DO NOT EDIT!

/*
Package systemProto is a generated protocol buffer package.

It is generated from these files:
	systemProto.proto

It has these top-level messages:
	System_ConnectDBServerC2S
	System_ConnectDBServerS2C
	System_ConnectTransferServerC2S
	System_ConnectTransferServerS2C
	System_ClientSessionOnlineC2S
	System_ClientSessionOfflineC2S
	System_ClientLoginSuccessC2S
*/
package systemProto

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

// 连接DB服务器
type System_ConnectDBServerC2S struct {
	ServerName       *string `protobuf:"bytes,1,req" json:"ServerName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *System_ConnectDBServerC2S) Reset()         { *m = System_ConnectDBServerC2S{} }
func (m *System_ConnectDBServerC2S) String() string { return proto.CompactTextString(m) }
func (*System_ConnectDBServerC2S) ProtoMessage()    {}

func (m *System_ConnectDBServerC2S) GetServerName() string {
	if m != nil && m.ServerName != nil {
		return *m.ServerName
	}
	return ""
}

// 连接DB服务器返回
type System_ConnectDBServerS2C struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *System_ConnectDBServerS2C) Reset()         { *m = System_ConnectDBServerS2C{} }
func (m *System_ConnectDBServerS2C) String() string { return proto.CompactTextString(m) }
func (*System_ConnectDBServerS2C) ProtoMessage()    {}

// 连接Transfer服务器
type System_ConnectTransferServerC2S struct {
	ServerName       *string `protobuf:"bytes,1,req" json:"ServerName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *System_ConnectTransferServerC2S) Reset()         { *m = System_ConnectTransferServerC2S{} }
func (m *System_ConnectTransferServerC2S) String() string { return proto.CompactTextString(m) }
func (*System_ConnectTransferServerC2S) ProtoMessage()    {}

func (m *System_ConnectTransferServerC2S) GetServerName() string {
	if m != nil && m.ServerName != nil {
		return *m.ServerName
	}
	return ""
}

// 连接Transfer服务器返回
type System_ConnectTransferServerS2C struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *System_ConnectTransferServerS2C) Reset()         { *m = System_ConnectTransferServerS2C{} }
func (m *System_ConnectTransferServerS2C) String() string { return proto.CompactTextString(m) }
func (*System_ConnectTransferServerS2C) ProtoMessage()    {}

// 通知游戏服务器用户上线
type System_ClientSessionOnlineC2S struct {
	SessionID        *uint64 `protobuf:"varint,1,req" json:"SessionID,omitempty"`
	Network          *string `protobuf:"bytes,2,req" json:"Network,omitempty"`
	Addr             *string `protobuf:"bytes,3,req" json:"Addr,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *System_ClientSessionOnlineC2S) Reset()         { *m = System_ClientSessionOnlineC2S{} }
func (m *System_ClientSessionOnlineC2S) String() string { return proto.CompactTextString(m) }
func (*System_ClientSessionOnlineC2S) ProtoMessage()    {}

func (m *System_ClientSessionOnlineC2S) GetSessionID() uint64 {
	if m != nil && m.SessionID != nil {
		return *m.SessionID
	}
	return 0
}

func (m *System_ClientSessionOnlineC2S) GetNetwork() string {
	if m != nil && m.Network != nil {
		return *m.Network
	}
	return ""
}

func (m *System_ClientSessionOnlineC2S) GetAddr() string {
	if m != nil && m.Addr != nil {
		return *m.Addr
	}
	return ""
}

// 通知游戏服务器用户下线
type System_ClientSessionOfflineC2S struct {
	SessionID        *uint64 `protobuf:"varint,1,req" json:"SessionID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *System_ClientSessionOfflineC2S) Reset()         { *m = System_ClientSessionOfflineC2S{} }
func (m *System_ClientSessionOfflineC2S) String() string { return proto.CompactTextString(m) }
func (*System_ClientSessionOfflineC2S) ProtoMessage()    {}

func (m *System_ClientSessionOfflineC2S) GetSessionID() uint64 {
	if m != nil && m.SessionID != nil {
		return *m.SessionID
	}
	return 0
}

// 通知游戏服务器用户登录成功
type System_ClientLoginSuccessC2S struct {
	UserID           *uint64 `protobuf:"varint,1,req" json:"UserID,omitempty"`
	UserName         *string `protobuf:"bytes,2,req" json:"UserName,omitempty"`
	SessionID        *uint64 `protobuf:"varint,3,req" json:"SessionID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *System_ClientLoginSuccessC2S) Reset()         { *m = System_ClientLoginSuccessC2S{} }
func (m *System_ClientLoginSuccessC2S) String() string { return proto.CompactTextString(m) }
func (*System_ClientLoginSuccessC2S) ProtoMessage()    {}

func (m *System_ClientLoginSuccessC2S) GetUserID() uint64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

func (m *System_ClientLoginSuccessC2S) GetUserName() string {
	if m != nil && m.UserName != nil {
		return *m.UserName
	}
	return ""
}

func (m *System_ClientLoginSuccessC2S) GetSessionID() uint64 {
	if m != nil && m.SessionID != nil {
		return *m.SessionID
	}
	return 0
}

func init() {
}
