// Code generated by protoc-gen-go.
// source: dbProto.proto
// DO NOT EDIT!

/*
Package dbProto is a generated protocol buffer package.

It is generated from these files:
	dbProto.proto

It has these top-level messages:
	DB_User_LoginC2S
	DB_User_LoginS2C
	DB_User_UpdateLastLoginTimeC2S
*/
package dbProto

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type DB_User_LoginC2S struct {
	Name             *string `protobuf:"bytes,1,req" json:"Name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DB_User_LoginC2S) Reset()         { *m = DB_User_LoginC2S{} }
func (m *DB_User_LoginC2S) String() string { return proto.CompactTextString(m) }
func (*DB_User_LoginC2S) ProtoMessage()    {}

func (m *DB_User_LoginC2S) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type DB_User_LoginS2C struct {
	ID               *uint64 `protobuf:"varint,1,opt" json:"ID,omitempty"`
	Name             *string `protobuf:"bytes,2,opt" json:"Name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DB_User_LoginS2C) Reset()         { *m = DB_User_LoginS2C{} }
func (m *DB_User_LoginS2C) String() string { return proto.CompactTextString(m) }
func (*DB_User_LoginS2C) ProtoMessage()    {}

func (m *DB_User_LoginS2C) GetID() uint64 {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return 0
}

func (m *DB_User_LoginS2C) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type DB_User_UpdateLastLoginTimeC2S struct {
	UserID           *uint64 `protobuf:"varint,1,req" json:"UserID,omitempty"`
	Time             *int64  `protobuf:"varint,2,req" json:"Time,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DB_User_UpdateLastLoginTimeC2S) Reset()         { *m = DB_User_UpdateLastLoginTimeC2S{} }
func (m *DB_User_UpdateLastLoginTimeC2S) String() string { return proto.CompactTextString(m) }
func (*DB_User_UpdateLastLoginTimeC2S) ProtoMessage()    {}

func (m *DB_User_UpdateLastLoginTimeC2S) GetUserID() uint64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

func (m *DB_User_UpdateLastLoginTimeC2S) GetTime() int64 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

func init() {
}
