// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ipc.proto

/*
Package ipc is a generated protocol buffer package.

It is generated from these files:
	ipc.proto

It has these top-level messages:
	Req
	Res
*/
package ipc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Req struct {
	ServiceIdentify string `protobuf:"bytes,1,opt,name=serviceIdentify" json:"serviceIdentify,omitempty"`
	UserSessionId   uint64 `protobuf:"varint,2,opt,name=userSessionId" json:"userSessionId,omitempty"`
	Data            []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *Req) Reset()                    { *m = Req{} }
func (m *Req) String() string            { return proto.CompactTextString(m) }
func (*Req) ProtoMessage()               {}
func (*Req) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Req) GetServiceIdentify() string {
	if m != nil {
		return m.ServiceIdentify
	}
	return ""
}

func (m *Req) GetUserSessionId() uint64 {
	if m != nil {
		return m.UserSessionId
	}
	return 0
}

func (m *Req) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Res struct {
	UserSessionIds []uint64 `protobuf:"varint,2,rep,packed,name=userSessionIds" json:"userSessionIds,omitempty"`
	Data           []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *Res) Reset()                    { *m = Res{} }
func (m *Res) String() string            { return proto.CompactTextString(m) }
func (*Res) ProtoMessage()               {}
func (*Res) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Res) GetUserSessionIds() []uint64 {
	if m != nil {
		return m.UserSessionIds
	}
	return nil
}

func (m *Res) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Req)(nil), "Req")
	proto.RegisterType((*Res)(nil), "Res")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Ipc service

type IpcClient interface {
	Transfer(ctx context.Context, opts ...grpc.CallOption) (Ipc_TransferClient, error)
}

type ipcClient struct {
	cc *grpc.ClientConn
}

func NewIpcClient(cc *grpc.ClientConn) IpcClient {
	return &ipcClient{cc}
}

func (c *ipcClient) Transfer(ctx context.Context, opts ...grpc.CallOption) (Ipc_TransferClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Ipc_serviceDesc.Streams[0], c.cc, "/Ipc/Transfer", opts...)
	if err != nil {
		return nil, err
	}
	x := &ipcTransferClient{stream}
	return x, nil
}

type Ipc_TransferClient interface {
	Send(*Req) error
	Recv() (*Res, error)
	grpc.ClientStream
}

type ipcTransferClient struct {
	grpc.ClientStream
}

func (x *ipcTransferClient) Send(m *Req) error {
	return x.ClientStream.SendMsg(m)
}

func (x *ipcTransferClient) Recv() (*Res, error) {
	m := new(Res)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Ipc service

type IpcServer interface {
	Transfer(Ipc_TransferServer) error
}

func RegisterIpcServer(s *grpc.Server, srv IpcServer) {
	s.RegisterService(&_Ipc_serviceDesc, srv)
}

func _Ipc_Transfer_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IpcServer).Transfer(&ipcTransferServer{stream})
}

type Ipc_TransferServer interface {
	Send(*Res) error
	Recv() (*Req, error)
	grpc.ServerStream
}

type ipcTransferServer struct {
	grpc.ServerStream
}

func (x *ipcTransferServer) Send(m *Res) error {
	return x.ServerStream.SendMsg(m)
}

func (x *ipcTransferServer) Recv() (*Req, error) {
	m := new(Req)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Ipc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Ipc",
	HandlerType: (*IpcServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Transfer",
			Handler:       _Ipc_Transfer_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "ipc.proto",
}

func init() { proto.RegisterFile("ipc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 176 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8f, 0xcd, 0x0a, 0xc2, 0x30,
	0x10, 0x84, 0x4d, 0x13, 0xc4, 0x2e, 0xfe, 0xc0, 0x9e, 0x82, 0x78, 0x08, 0x55, 0x24, 0xa7, 0x22,
	0xfa, 0x04, 0x1e, 0x7b, 0x8d, 0xbe, 0x40, 0x6d, 0xb7, 0x90, 0x4b, 0x7f, 0xb2, 0x55, 0xf0, 0xed,
	0xa5, 0xbd, 0xb5, 0x78, 0x19, 0x86, 0x8f, 0x61, 0x86, 0x81, 0xd8, 0xb7, 0x45, 0xda, 0x86, 0xa6,
	0x6f, 0x12, 0x0f, 0xd2, 0x51, 0x87, 0x16, 0x76, 0x4c, 0xe1, 0xe3, 0x0b, 0xca, 0x4a, 0xaa, 0x7b,
	0x5f, 0x7d, 0xb5, 0x30, 0xc2, 0xc6, 0x6e, 0x8e, 0xf1, 0x04, 0x9b, 0x37, 0x53, 0x78, 0x10, 0xb3,
	0x6f, 0xea, 0xac, 0xd4, 0x91, 0x11, 0x56, 0xb9, 0x29, 0x44, 0x04, 0x55, 0xe6, 0x7d, 0xae, 0xa5,
	0x11, 0x76, 0xed, 0x46, 0x9f, 0xdc, 0x87, 0x29, 0xc6, 0x33, 0x6c, 0x27, 0x59, 0xd6, 0x91, 0x91,
	0x56, 0xb9, 0x19, 0xfd, 0x57, 0x71, 0x3d, 0x82, 0xcc, 0xda, 0x02, 0x0f, 0xb0, 0x7a, 0x86, 0xbc,
	0xe6, 0x8a, 0x02, 0xaa, 0xd4, 0x51, 0xb7, 0x1f, 0x94, 0x93, 0x85, 0x15, 0x17, 0xf1, 0x5a, 0x8e,
	0xcf, 0x6e, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb2, 0xf1, 0x4c, 0x62, 0xe6, 0x00, 0x00, 0x00,
}
